---
title: "Time Series project"
output: html_document
date: "2024-03-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r, include=FALSE}
require(astsa)
library(quantmod)
library(ggplot2)
library(tseries)
library(prophet)
library(tsfknn)
library(mFilter)


#data extraction and stock market indicators
getSymbols("^GSPC",src="yahoo",from="2015-01-01",to = "2019-12-31")
date = index(GSPC)
date = as.Date(date)
head(GSPC)
chartSeries(GSPC,TA = NULL)
chartSeries(GSPC,TA=c(addVo(),addBBands(),addMACD()))

```

```{r}
GSPC_2015 <- window(GSPC, start="2015-01-01", end="2015-12-31")
GSPC_2016 <- window(GSPC, start="2016-01-01", end="2016-12-31")
GSPC_2017 <- window(GSPC, start="2017-01-01", end="2017-12-31")
GSPC_2018 <- window(GSPC, start="2018-01-01", end="2018-12-31")
GSPC_2019 <- window(GSPC, start="2019-01-01", end="2019-12-31")


plot.ts(GSPC$GSPC.Open, main="Time Series Plot", xlab="2015-2019", ylab="S&P 500 Opening Value")
plot.ts(GSPC_2015$GSPC.Open, main="Time Series Plot", xlab="2015", ylab="S&P 500 Opening Value")
plot.ts(GSPC_2016$GSPC.Open, main="Time Series Plot", xlab="2016", ylab="S&P 500 Opening Value")
plot.ts(GSPC_2017$GSPC.Open, main="Time Series Plot", xlab="2017", ylab="S&P 500 Opening Value")
plot.ts(GSPC_2018$GSPC.Open, main="Time Series Plot", xlab="2018", ylab="S&P 500 Opening Value")
plot.ts(GSPC_2019$GSPC.Open, main="Time Series Plot", xlab="2019", ylab="S&P 500 Opening Value")




monthplot(ts(GSPC_2015$GSPC.Open, frequency=12))
monthplot(ts(GSPC_2016$GSPC.Open, frequency=12))
monthplot(ts(GSPC_2017$GSPC.Open, frequency=12))
monthplot(ts(GSPC_2018$GSPC.Open, frequency=12))
monthplot(ts(GSPC_2019$GSPC.Open, frequency=12))



```

```{r}
data_ts <- ts(GSPC)
data_clean <- data.frame(na.omit(data_ts))
# Creating a sequence of mid-points of two weeks from January 2015
# Assuming a 20-day month for simplicity and starting from "1" for beginning-January 2015 because average of 20 weekdays every month
mid_points <- seq(1, by = 10, length.out = 120)  # every 2 weeks over the 5 years

# subset data_clean dataframe to only include these mid-points
data_subset <- data_clean[mid_points, ]
data_subset <- data.frame(na.omit(data_subset))

#difference data added to dataframe
data_subset$Open.Differenced <- c(NA, NA, diff(data_subset$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset <- na.omit(data_subset)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset$Open.Differenced, lag.max = 120, main = "ACF for every 2 weeks for GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset$Open.Differenced, lag.max = 120, main = "PACF for every 2 weeks for GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)



#same thing but now looking at monthly instead of every two weeks


data_ts <- ts(GSPC)
data_clean <- data.frame(na.omit(data_ts))
# Creating a sequence of mid-points of every month from January 2015
# Assuming a 20-day month for simplicity and starting from "1" for beginning January 2015 because average of 20 weekdays every month
mid_points_monthly <- seq(1, by = 20, length.out = 60)  # every month over the 5 years

# subset data_clean dataframe to only include these mid-points
data_subset_monthly <- data_clean[mid_points_monthly, ]
data_subset_monthly <- data.frame(na.omit(data_subset_monthly))

#difference data added to dataframe
data_subset_monthly$Open.Differenced <- c(NA, NA, diff(data_subset_monthly$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_monthly <- na.omit(data_subset_monthly)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_monthly$Open.Differenced, lag.max = 60, main = "ACF for every month for GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_monthly$Open.Differenced, lag.max = 60, main = "PACF for every month for GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)







fit <- arima(data_subset$Open.Differenced, order=c(1, 2, 4))
residuals <- residuals(fit)
plot(residuals, type='o', main='Residuals over Time', ylab='Residuals', xlab='Time')
abline(h=0, col='red')



# Apply Baxter-King filter
bk_filtered <- bkfilter(GSPC$GSPC.Open, pl=6, pu=32)
# For daily data, assuming about 252 trading days per year
# bk_filtered <- bkfilter(GSPC$GSPC.Open, pl=6*252, pu=32*252)

# Plot the cyclical component
plot(bk_filtered$cycle, main="Cyclical Component of S&P 500", ylab="Cycle", xlab="Time")

```

```{r}
points_2015 <- seq(1, by = 2, length.out = 125)  # every other day for 2015

# subset data_clean dataframe to only include these mid-points
data_subset_2015 <- data_clean[points_2015, ]
data_subset_2015 <- data.frame(na.omit(data_subset_2015))

#difference data added to dataframe
data_subset_2015$Open.Differenced <- c(NA, NA, diff(data_subset_2015$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_2015 <- na.omit(data_subset_2015)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_2015$Open.Differenced, lag.max = 125, main = "ACF for every 2 days for 2015 GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_2015$Open.Differenced, lag.max = 125, main = "PACF for every 2 days for 2015 GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)


fit_2015 <- arima(data_subset_2015$Open.Differenced, order=c(2, 2, 1))
residuals <- residuals(fit_2015)
plot(residuals, type='o', main='Residuals over Time', ylab='Residuals', xlab='2015')
abline(h=0, col='red')

```

```{r}
points_2016 <- seq(252, by = 2, length.out = 125)  # every other day for 2016

# subset data_clean dataframe to only include these mid-points
data_subset_2016 <- data_clean[points_2016, ]
data_subset_2016 <- data.frame(na.omit(data_subset_2016))

#difference data added to dataframe
data_subset_2016$Open.Differenced <- c(NA, diff(data_subset_2016$GSPC.Open, differences = 1))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_2016 <- na.omit(data_subset_2016)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_2016$Open.Differenced, lag.max = 125, main = "ACF for every 2 days for 2016 GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_2016$Open.Differenced, lag.max = 125, main = "PACF for every 2 days for 2016 GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)

fit_2016 <- arima(data_subset_2016$Open.Differenced, order=c(2, 2, 0))
residuals <- residuals(fit_2016)
plot(residuals, type='o', main='Residuals over Time', ylab='Residuals', xlab='2016')
abline(h=0, col='red')

```

```{r}
points_2017 <- seq(503, by = 2, length.out = 125)  # every other day for 2017

# subset data_clean dataframe to only include these mid-points
data_subset_2017 <- data_clean[points_2017, ]
data_subset_2017 <- data.frame(na.omit(data_subset_2017))

#difference data added to dataframe
data_subset_2017$Open.Differenced <- c(NA, NA, diff(data_subset_2017$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_2017 <- na.omit(data_subset_2017)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_2017$Open.Differenced, lag.max = 125, main = "ACF for every 2 days for 2017 GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_2017$Open.Differenced, lag.max = 125, main = "PACF for every 2 days for 2017 GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)

```

```{r}
points_2018 <- seq(755, by = 2, length.out = 125)  # every other day for 2018

# subset data_clean dataframe to only include these mid-points
data_subset_2018 <- data_clean[points_2018, ]
data_subset_2018 <- data.frame(na.omit(data_subset_2018))

#difference data added to dataframe
data_subset_2018$Open.Differenced <- c(NA, NA, diff(data_subset_2018$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_2018 <- na.omit(data_subset_2018)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_2018$Open.Differenced, lag.max = 125, main = "ACF for every 2 days for 2018 GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_2018$Open.Differenced, lag.max = 125, main = "PACF for every 2 days for 2018 GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)

```

```{r}
points_2019 <- seq(1007, by = 2, length.out = 125)  # every other day for 2019

# subset data_clean dataframe to only include these mid-points
data_subset_2019 <- data_clean[points_2019, ]
data_subset_2019 <- data.frame(na.omit(data_subset_2019))

#difference data added to dataframe
data_subset_2019$Open.Differenced <- c(NA, NA, diff(data_subset_2019$GSPC.Open, differences = 2))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_2019 <- na.omit(data_subset_2019)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_2019$Open.Differenced, lag.max = 125, main = "ACF for every 2 days for 2019 GSPC.Open")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_2019$Open.Differenced, lag.max = 125, main = "PACF for every 2 days for 2019 GSPC.Open")



# Reset only the 'mar' parameter after plotting
par(mar = original_mar)

```



Same thing but now seasanaly differencing data
```{r}
data_ts <- ts(GSPC)
data_clean <- data.frame(na.omit(data_ts))
# Creating a sequence of mid-points of every month from January 2015
# Assuming a 20-day month for simplicity and starting from "1" for beginning January 2015 because average of 20 weekdays every month
mid_points_monthly <- seq(1, by = 20, length.out = 60)  # every month over the 5 years

# subset data_clean dataframe to only include these mid-points
data_subset_monthly <- data_clean[mid_points_monthly, ]
data_subset_monthly <- data.frame(na.omit(data_subset_monthly))

# This adds a column to your data frame with NAs for the first 12 values
data_subset_monthly$Open.Seasonly_Differenced <- c(rep(NA, 12), diff(data_subset_monthly$GSPC.Open, lag = 12, differences = 1))

# Now that 'Open.Differenced' is part of data_subset, remove the row with NA
data_subset_monthly <- na.omit(data_subset_monthly)

# Save the original graphical parameters so you can reset them later
original_par <- par()
original_mar <- par("mar")

# Increase the top margin
par(mar = c(5, 4, 6, 2))

# Calculate and plot the ACF for the subset data
acf(data_subset_monthly$Open.Seasonly_Differenced, lag.max = 60, main = "ACF for every month with monthly data differenced")
# Calculate and plot the PACF for the subset data 
pacf(data_subset_monthly$Open.Seasonly_Differenced, lag.max = 60, main = "PACF for every month with monthly data differenced")



#Reset only the 'mar' parameter after plotting
par(mar = original_mar)



x <- c()
x <- rnorm(12)
for (i in 13:144)
  x[i] <- .8 * x[i-12] + rnorm(1)
acf(x,lag.max=60)

```


